name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.3

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: |
          echo "REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN" >> .env.production
          echo "REACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID" >> .env.production
          CI='' npm run build
        env:
          REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Download build folder from S3
        run: |
          aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/build ./build

      - name: Zip build folder
        run: |
            cd build
            zip -r ../artifact.zip .
            cd ..

      - name: Create Amplify Deployment
        id: amplify_deploy
        run: |
            response=$(aws amplify create-deployment \
              --region ap-south-1 \
              --app-id ${{ secrets.AMPLIFY_APP_ID }} \
              --branch-name staging)
            
            echo "$response"
            echo "zip_url=$(echo $response | jq -r '.zipUploadUrl')" >> $GITHUB_OUTPUT
            echo "job_id=$(echo $response | jq -r '.jobId')" >> $GITHUB_OUTPUT

      - name: Upload to Amplify Zip URL
        run: |
            curl -T artifact.zip "${{ steps.amplify_deploy.outputs.zip_url }}"

      - name: Trigger Amplify Deployment
        run: |
            aws amplify start-deployment \
              --region ap-south-1 \
              --app-id ${{ secrets.AMPLIFY_APP_ID }} \
              --branch-name staging \
              --job-id ${{ steps.amplify_deploy.outputs.job_id }} \

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
